apiVersion: argoproj.io/v1alpah1
kind: Application
metadata:
  name: cleanup-operator
spec:
  project: root
  source:
    repourl: https://btwseeu78.github.io/kube-cleanup-operator/
    targetRevision: 0.1.2
    chart: kube-cleanup-operator
    helm:
      values: |
        cleanup:
          {{- if .Values.cluster.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml .Values.cluster.imagePullSecrets | nindent 12}}
          {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: "default"